### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by phodal** [unit-mesh/auto-dev-vscode#21]
```javascript
2024-04-30 10:10:19.097 [error] ReferenceError: self is not defined
    at /Volumes/source/ai/auto-dev-vscode/node_modules/onnxruntime-web/dist/ort-web.min.js:6:316
    at Module.<anonymous> (/Volumes/source/ai/auto-dev-vscode/dist/transformers-DJA0Jt4V.js:14984:3)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at Function.c._load (node:electron/js2c/node_init:2:13672)
    at Function.h._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:175:5602)
    at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:29719)
    at Function.t._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:35279)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at /Volumes/source/ai/auto-dev-vscode/src/code-search/embedding/TransformersEmbeddingProvider.ts:15:35
    at Function.getInstance (/Volumes/source/ai/auto-dev-vscode/src/code-search/embedding/TransformersEmbeddingProvider.ts:15:29)
    at _TransformersEmbeddingProvider.embed (/Volumes/source/ai/auto-dev-vscode/src/code-search/embedding/TransformersEmbeddingProvider.ts:38:19)
```

**Comment by phodal** [comment]
@CGQAQ 

```
2024-04-30 11:01:25.893 [error] TypeError: Cannot read properties of undefined (reading 'create')
    at constructSession (/Volumes/source/ai/auto-dev-vscode/node_modules/@xenova/transformers/src/models.js:140:39)
    at async Promise.all (index 1)
    at Function.from_pretrained (/Volumes/source/ai/auto-dev-vscode/node_modules/@xenova/transformers/src/models.js:793:20)
    at Function.from_pretrained (/Volumes/source/ai/auto-dev-vscode/node_modules/@xenova/transformers/src/models.js:5490:20)
    at async Promise.all (index 1)
    at loadItems (/Volumes/source/ai/auto-dev-vscode/node_modules/@xenova/transformers/src/pipelines.js:3277:5)
    at pipeline (/Volumes/source/ai/auto-dev-vscode/node_modules/@xenova/transformers/src/pipelines.js:3217:21)
    at Function.getInstance (/Volumes/source/ai/auto-dev-vscode/src/code-search/embedding/TransformersEmbeddingProvider.ts:25:20)
    at _TransformersEmbeddingProvider.embed (/Volumes/source/ai/auto-dev-vscode/src/code-search/embedding/TransformersEmbeddingProvider.ts:38:19)
```

**Comment by phodal** [comment]
```bash
Activating extension 'Phodal.autodev' failed: Could not dynamically require "../bin/napi-v3/darwin/x64/onnxruntime_binding.node". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work..
```
